/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch 设计稿配色 — 智伴智慧社区养老
        'surface-container-low': '#f2f4f7',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ffb59e',
        'on-tertiary-fixed-variant': '#00531c',
        'primary-container': '#0066ff',
        'on-error-container': '#93000a',
        'inverse-primary': '#b3c5ff',
        'on-primary': '#ffffff',
        'outline': '#727687',
        'secondary': '#a53b18',
        'on-secondary-fixed-variant': '#852401',
        'on-primary-fixed': '#001849',
        'background': '#f7f9fc',
        'secondary-container': '#ff7d54',
        'on-background': '#191c1e',
        'on-surface-variant': '#424656',
        'on-surface': '#191c1e',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#e6ffe1',
        'surface-bright': '#f7f9fc',
        'primary-fixed': '#dae1ff',
        'on-primary-container': '#f8f7ff',
        'primary-fixed-dim': '#b3c5ff',
        'tertiary': '#006825',
        'surface-container-high': '#e6e8eb',
        'inverse-on-surface': '#eff1f4',
        'on-secondary-fixed': '#3a0a00',
        'outline-variant': '#c2c6d8',
        'tertiary-fixed': '#72fe88',
        'surface-dim': '#d8dadd',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#002107',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6e1c00',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#003fa4',
        'surface-container-highest': '#e0e3e6',
        'tertiary-fixed-dim': '#53e16f',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#0054d6',
        'inverse-surface': '#2d3133',
        'tertiary-container': '#008432',
        'on-error': '#ffffff',
        'surface-container': '#eceef1',
        'surface': '#f7f9fc',
        'primary': '#0050cb',
        'secondary-fixed': '#ffdbd0',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        '24': '24px',
      },
      spacing: {
        'unit': '8px',
        'container-padding-mobile': '20px',
        'gutter': '24px',
        'container-padding-desktop': '40px',
        'bento-gap': '24px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'label-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': ['16px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'soft-care': '0 8px 24px rgba(0, 0, 0, 0.04)',
        'soft-care-hover': '0 12px 32px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
